GET http://localhost:5000/users

###

POST http://localhost:5000/users HTTP/1.1
Content-Type: application/json

{   
    "userName": "Marielle2",
    "userSurname": "Torbay",
    "userFirebaseID": "jfjezio7733",
    "userLoans": [
        {
            "googleId": "livre1",
            "loanDate": "2012-04-21T18:25:43-05:00",
            "endLoanDate": "2022-04-21T18:25:43-05:00",
            "loanRenewed": false
        }
    ]
}

###

POST http://localhost:5000/users/update/626102c25295b4ffdd8a6958 HTTP/1.1
content-type: application/json

{
    "userLoans": [
        {
            "googleId": "livre test fdezfzs",
            "loanDate": "2012-04-21T18:25:43-05:00",
            "endLoanDate": "2022-04-21T18:25:43-05:00",
            "loanRenewed": false
        }
    ]
}